# Generated by Django 3.2.8 on 2021-12-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211216_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.ManyToManyField(blank=True, to='authentication.Budget'),
        ),
    ]
