# Generated by Django 3.2.8 on 2021-12-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211216_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
