# Generated by Django 3.2.8 on 2021-12-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20211216_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.ManyToManyField(blank=True, to='authentication.Role'),
        ),
    ]
