# Generated by Django 3.2.8 on 2021-12-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_name',
        ),
    ]
