# Generated by Django 3.2.8 on 2021-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('aisleId', models.AutoField(primary_key=True, serialize=False)),
                ('aisleName', models.CharField(max_length=10)),
            ],
        ),
    ]
