# Generated by Django 3.2.8 on 2021-12-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aisles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('salesPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('manufactureringCost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aisleName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aisles.aisle')),
            ],
        ),
    ]
