# Generated by Django 3.2.8 on 2021-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('salesPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('manufactureringCost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aisleName', models.ManyToManyField(blank=True, to='products.Aisle')),
            ],
        ),
    ]
