# Generated by Django 3.2.8 on 2021-12-17 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
